"""Orchestrator contracts (INTERFACES §1.1; DOMAIN-MODEL §4.15)."""

from datetime import datetime
from typing import Literal

from pydantic import Field

from walk.budgets.models import Budget, CostCategory
from walk.common.ids import (
    BugId,
    DebateId,
    EvidenceId,
    ModelId,
    PhaseId,
    ProjectKey,
    RetrospectiveId,
    WorkItemId,
)
from walk.common.models import FrozenModel, WalkModel
from walk.common.roles import AgentRole
from walk.model_router.models import TaskProfile, UsageReport
from walk.permissions.models import ApprovalRequest
from walk.runtime.models import AgentRun
from walk.workflow.models import Phase, WorkItemState


class RouteDecision(FrozenModel):
    """`TaskRouter.route` result: who works on an item, for what, with which needs."""

    role: AgentRole = Field(description="Role that works on the item.")
    purpose: Literal[
        "IMPLEMENT", "DESIGN", "REVIEW", "QC", "TRIAGE", "DEBATE", "PLAN", "ANALYSIS", "RETRO"
    ] = Field(description="Task template of the run.")
    profile: TaskProfile = Field(description="What the router needs to pick a model.")
    cross_model_review: bool = Field(
        description="§23: the role prefers a model other than the implementer's."
    )


class KernelStatus(FrozenModel):
    """§87 dashboard snapshot (`walk status`)."""

    project_key: ProjectKey = Field(description="Project of the kernel.")
    paused: bool = Field(description="Project paused by the user.")
    current_phase: Phase | None = Field(description="Phase in progress, if any.")
    phase_progress: dict[WorkItemState, int] = Field(
        description="Work items per state in the current phase (all items without a phase)."
    )
    gdd_coverage: dict[str, float] = Field(description="§74 coverage per GDD area.")
    active_runs: list[AgentRun] = Field(description="Runs running or paused.")
    blocked_items: list[WorkItemId] = Field(description="Work items in BLOCKED.")
    pending_approvals: list[ApprovalRequest] = Field(description="Approvals awaiting a decision.")
    open_debates: list[DebateId] = Field(description="Debates not yet resolved.")
    model_usage: dict[ModelId, UsageReport] = Field(description="Usage per model.")
    qc_status: dict[str, int] = Field(description="QC outcomes by status.")
    build_status: str | None = Field(description="Latest build result, if any.")
    budgets: list[Budget] = Field(description="Budgets applicable to the project.")
    open_improvement_candidates: int = Field(description="Improvement candidates awaiting review.")


class PhaseEvidencePackage(WalkModel):
    """§69 phase evidence package.

    Generated by orchestrator.EvidencePackager into `.ai/phases/PHASE-NN/evidence-package.md`.
    """

    phase_id: PhaseId = Field(description="Phase under review.")
    gate_round: int = Field(description="Gate round the package was built for.")
    generated_at: datetime = Field(description="When it was generated.")
    gdd_coverage: dict[str, float] = Field(description="GDD Coverage (§74) per GDD area.")
    stories_completed: list[WorkItemId] = Field(description="Stories Completed.")
    stories_open: list[WorkItemId] = Field(description="Stories still open.")
    open_issues: list[BugId] = Field(description="Open Issues.")
    known_limitations: list[str] = Field(description="Known Limitations.")
    qc_status: str = Field(description="QC Status.")
    automated_tests: list[EvidenceId] = Field(description="Automated Tests.")
    performance_metrics: list[EvidenceId] = Field(description="Performance Metrics.")
    playable_build: EvidenceId | None = Field(description="Playable Build.")
    gameplay_recordings: list[EvidenceId] = Field(description="Gameplay Recording.")
    screenshots: list[EvidenceId] = Field(description="Screenshots.")
    design_review: EvidenceId | None = Field(description="Design Review.")
    technical_review: EvidenceId | None = Field(description="Technical Review.")
    risk_summary: str = Field(description="Risk Summary.")
    production_cost: dict[CostCategory, float] = Field(description="Production Cost (§84).")
    retrospective_id: RetrospectiveId | None = Field(
        default=None, description="Phase retrospective (§115), once written."
    )
