"""Generate docs/03-traceability/NAME-REGISTER.md from `NEW NAME:` / `RELOCATE:` notes.

Every story that introduces a public name not yet defined in docs/01-architecture/ marks it
in its Notes with ``NEW NAME:`` (or a placement change with ``RELOCATE:``). This script
collects those notes per story so an implementer or reviewer can see, in one place, which
names exist only at story level. Re-run after any story change::

    py -3 scripts/build_name_register.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WBS_DIR = ROOT / "docs" / "02-work-breakdown"
OUT = ROOT / "docs" / "03-traceability" / "NAME-REGISTER.md"
STORY_SPLIT = re.compile(r"(?m)^(?=### E\d{2}-[SRXB]\d{2} )")
MARK = re.compile(r"`?(NEW NAME|RELOCATE):`?")


def clean(text: str) -> str:
    text = text.strip().lstrip("-").strip()
    text = text.replace("|", "\\|")
    return re.sub(r"\s+", " ", text)


def main() -> None:
    rows: list[tuple[str, str, str, str]] = []
    for f in sorted(WBS_DIR.glob("EPIC-*.md")):
        for part in STORY_SPLIT.split(f.read_text(encoding="utf-8")):
            m = re.match(r"### (E\d{2}-[SRXB]\d{2}) ", part)
            owner = m.group(1) if m else f"{f.stem} header"
            for line in part.splitlines():
                mk = MARK.search(line)
                if not mk:
                    continue
                text = clean(line[mk.end() :])
                if text:
                    rows.append((owner, mk.group(1), text, f.name))
    lines = [
        "# Story-level Name Register",
        "",
        "Generated by `scripts/build_name_register.py` from `NEW NAME:` and `RELOCATE:` notes in",
        "`docs/02-work-breakdown/EPIC-*.md`. Do not edit by hand; re-run the script.",
        "",
        "Rules (WBS.md §2 rule 6):",
        "",
        "- A name listed here is introduced by the named story. The story text is authoritative for",
        "  its exact signature until the name is promoted into `docs/01-architecture/`.",
        "- A story that changes a cross-package contract updates INTERFACES.md / DOMAIN-MODEL.md in",
        "  the same commit (CONVENTIONS.md §4); the epic review task checks this register for names",
        "  that were promoted but are still story-local, and for conflicting definitions.",
        "",
        f"Entries: {len(rows)}",
        "",
        "| Story | Kind | Names / note | File |",
        "|---|---|---|---|",
    ]
    lines += [f"| `{o}` | {k} | {t} | `{fn}` |" for o, k, t, fn in rows]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} entries")


if __name__ == "__main__":
    main()
