"""Generate docs/03-traceability/REQ-TRACEABILITY.md from story Requirements fields.

Reads ``requirements/WAL_K_REQ.md`` (if present) for section titles, every ``EPIC-*.md`` for
``**Requirements:** §NN, ...`` lines, and writes a section → stories matrix plus the list of
spec sections no story cites. Re-run after any story change::

    py -3 scripts/build_traceability.py
"""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WBS_DIR = ROOT / "docs" / "02-work-breakdown"
REQ = ROOT / "requirements" / "WAL_K_REQ.md"
OUT = ROOT / "docs" / "03-traceability" / "REQ-TRACEABILITY.md"
SEC_RE = re.compile(r"§(\d{1,3})(?:\.(\d+))?")
STORY_RE = re.compile(
    r"(?m)^### (E\d{2}-[SRXB]\d{2}) — (.+)\n(?:.*\n){0,8}?\*\*Requirements:\*\*\s*(.+)$"
)


def spec_sections() -> dict[int, str]:
    titles: dict[int, str] = {}
    if REQ.exists():
        for line in REQ.read_text(encoding="utf-8").splitlines():
            m = re.match(r"^# (\d{1,3})\. (.+)$", line)
            if m:
                titles[int(m.group(1))] = m.group(2).strip()
    return titles


def main() -> None:
    titles = spec_sections()
    by_section: dict[int, list[tuple[str, str]]] = defaultdict(list)
    story_epic: dict[str, str] = {}
    for f in sorted(WBS_DIR.glob("EPIC-*.md")):
        text = f.read_text(encoding="utf-8")
        for m in STORY_RE.finditer(text):
            sid, title, reqs = m.group(1), m.group(2).strip(), m.group(3)
            story_epic[sid] = f.name
            for s in SEC_RE.finditer(reqs):
                sec = int(s.group(1))
                if (sid, title) not in by_section[sec]:
                    by_section[sec].append((sid, title))
    all_secs = sorted(set(titles) | set(by_section))
    uncovered = [s for s in all_secs if s not in by_section]
    lines = [
        "# Requirement → Story Traceability",
        "",
        "Generated by `scripts/build_traceability.py` from the `**Requirements:**` field of every",
        "story in `docs/02-work-breakdown/EPIC-*.md`. Do not edit by hand; re-run the script.",
        "",
        f"- Spec sections known: {len(all_secs)}",
        f"- Sections covered by at least one story: {len(by_section)}",
        f"- Stories with requirement references: {len(story_epic)}",
        "",
        "## Coverage matrix",
        "",
        "| § | Section | Stories |",
        "|---|---|---|",
    ]
    for sec in all_secs:
        stories = ", ".join(f"`{sid}`" for sid, _ in sorted(by_section.get(sec, []))) or "—"
        lines.append(f"| §{sec} | {titles.get(sec, '')} | {stories} |")
    lines += ["", "## Sections not cited by any story", ""]
    if uncovered:
        lines += [f"- §{s} {titles.get(s, '')}" for s in uncovered]
    else:
        lines.append("None.")
    lines += ["", "## Stories by epic file", ""]
    per_file: dict[str, list[str]] = defaultdict(list)
    for sid, fn in story_epic.items():
        per_file[fn].append(sid)
    for fn in sorted(per_file):
        lines.append(f"- `{fn}`: {len(per_file[fn])} stories")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(
        f"wrote {OUT.relative_to(ROOT)}: {len(by_section)}/{len(all_secs)} sections covered, "
        f"{len(uncovered)} uncovered"
    )


if __name__ == "__main__":
    main()
